### ISSUE TITLE
bug: patching fails with java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by FineFindus** [inotia00/ReVanced_Extended#1225]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube v.18.27.35

### Bug description

Running the CLI when patching fails with `java.lang.reflect.InvocationTargetException` caused by `Caused by: java.lang.NoClassDefFoundError: com/android/tools/smali/dexlib2/AccessFlags`

### Steps to reproduce

1. Run `java -jar revanced-cli-2.22.1-dev.1-all.jar -a youtube_18.27.35.apk -b revanced-patches-2.186.4.jar -m revanced-integrations-0.114.4.apk -o output.apk`
2. Notice error

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping Add splash animation: Excluded by default 
INFO: Skipping Custom branding icon MMT: Excluded by default 
INFO: Skipping Custom branding icon Revancify red: Excluded by default 
INFO: Skipping Disable landscape mode: Excluded by default 
INFO: Skipping Enable debug logging: Excluded by default 
INFO: Skipping Force hide player button background: Excluded by default 
INFO: Skipping Force premium heading: Excluded by default 
INFO: Skipping Hide double tap overlay filter: Excluded by default 
INFO: Skipping MaterialYou: Excluded by default 
INFO: Merging revanced-integrations-0.114.4.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:319)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:167)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NoClassDefFoundError: com/android/tools/smali/dexlib2/AccessFlags
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<init>(RemoteEmbeddedPlayerFingerprint.kt:11)
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<clinit>(RemoteEmbeddedPlayerFingerprint.kt)
	at app.revanced.patches.youtube.utils.integrations.patch.IntegrationsPatch.<init>(IntegrationsPatch.kt:20)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.android.tools.smali.dexlib2.AccessFlags
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 27 more
```

### Additional context

Seems to be caused by https://github.com/inotia00/revanced-patches/commit/65af056d5b2c0834ab8f5171120b1574e500a664

### Device Environment

Linux/CLI

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Incompatible with the official ReVanced CLI because the dependency has changed
Use the CLI with this change applied
https://github.com/inotia00/revanced-cli/releases
